# Generated by Django 5.1.2 on 2024-10-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='title_en',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='title_ru',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
